cpp=g++ 
prom=server
source=main.cpp vari_defini.cpp communi.cpp fight.cpp read.cpp write.cpp heart_beat.cc card.cpp player.cpp tool.cpp vari.cpp
tail=-std=c++11 -lpthread -g
$(prom): $(source)
					 $(cpp) -o $(prom) $(source) $(tail) 
